version: "3.9"

services:
  nginx:
    image: nginx:1.27-alpine
    command: ["nginx", "-g", "daemon off;"]
    container_name: nginx
    ports:
      - "8090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network

  app:
    image: php:8.3-fpm-alpine
    container_name: php-fpm
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse
    environment:
      - CLICKHOUSE_PASSWORD=
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_DEFAULT_USER: admin
      CLICKHOUSE_DEFAULT_PASSWORD: admin123
    volumes:
      - ./clickhouse/clickhouse-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - app-network

  fluentbit:
    image: fluent/fluent-bit:3.0.4
    container_name: fluentbit
    depends_on:
      - clickhouse
      - nginx
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - ./logs:/var/log/simulator:ro
      - nginx_logs:/var/log/nginx
    command:
      ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
    networks:
      - app-network

volumes:
  clickhouse_data:
  nginx_logs:

networks:
  app-network:
